Admin
zachlearnscode/beerOnTheWall pull request #5
Opened 2021-03-04 05:03 UTC by ryandeba

This is the beginnings of an admin interface for us to manually manage the beer data. Right now it can only delete beers, but we could improve it later by letting you edit the name, beer name, and date if we want to.

To see the admin button, you just have to have "admin" somewhere in the query string (e.g. `http://localhost:8080?admin` or `https://zachlearnscode.github.io/beerOnTheWall/?admin`)

2021-03-04 05:07 UTC, ryandeba commented
Just realized that this is always deleting data from the server on ryandeba.com. If we merge #3, we should change that to modify the localstorage data when running locally.

2021-03-05 18:21 UTC, ryandeba commented on src/components/Admin.vue
> +            v-for="(beer, index) in beers.filter(b => !b.full)"
I like the idea of not showing non-drank beers, but filtering it on the v-for may result in the incorrect `index`, which would be a problem when you go to remove it.

2021-03-05 18:28 UTC, zachlearnscode commented on src/components/Admin.vue
> +            v-for="(beer, index) in beers.filter(b => !b.full)"
That's a good call. Can we say beers.indexOf(beer) instead of {{index}} in the innerText of the elements?

2021-03-05 18:34 UTC, zachlearnscode commented on src/components/Admin.vue
> +            v-for="(beer, index) in beers.filter(b => !b.full)"
That appears to have worked.

2021-03-05 18:54 UTC, zachlearnscode requested changes
@ryandeba I just took a stab at the change you mentioned for removing beers on a local server. I'm sure it needs your attention ;)

2021-03-05 19:46 UTC, ryandeba commented on src/components/Admin.vue
> +            v-for="(beer, index) in beers.filter(b => !b.full)"
Nice! Yeah indexOf should work in this instance. Gotta be careful with that when working with an array of objects though since objects that look the same are not the same (e.g. `{foo: 1} !== {foo: 1}`)

2021-03-05 20:01 UTC, ryandeba commented on src/components/Admin.vue
> +      } else {
Awesome! You've got the right idea here, just see a couple of things:
- localStorage: `wal` and `walls` should be `wall`, and we'll want to stringify the data on `setItem`
- Splicing the array is going to remove the beer (e.g "we have 99 beers total" > splice > "we have 98 beers total"). I think we can just set the beer at the specific index back to an empty object (e.g. `data[index] = {};`)
- Ideally the `data-changed` event should get emitted regardless of environment


Untested, but I think this might do the trick:
```
remove(index) {
	Promise.resolve()
		.then(() => {		
			if (process?.env?.NODE_ENV === "development") {
				let data = localStorage.getItem("wall");
				data = JSON.parse(data);
				data[index] = {};
				localStorage.setItem("wall", JSON.stringify(data));
			} else {
				return fetch("https://ryandeba.com/beer", {
					method: "DELETE",
					headers: {
						"Content-Type": "application/json",
					},
					body: JSON.stringify({
						index: index,
					}),
				});
			}
		}).then(() => {
			this.$emit("data-changed");
		});
},
```

2021-03-05 22:10 UTC, zachlearnscode commented on src/components/Admin.vue
> +      } else {
I've pushed those changes, but until I merge this branch, I don't think I have access to development mode in admin branch. Or maybe I'm just trying to run development mode incorrectly? npm run serve --mode development ??

2021-03-05 23:15 UTC, merged